name: Build

on:
  push:
    branches: ['*']
    paths-ignore:
      - README.md
      - resources
  pull_request:
    branches: ['*']
    paths-ignore:
      - README.md
      - resources
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Install Python
        run: sudo apt-get -y install python

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # we need to have the full history and tags for `git describe` to work
          fetch-depth: 0

      # idk why this is needed, the checkout aciton already does this
      - name: Add git safe directory
        run: git config --global --add safe.directory "$PWD"

      - name: Build NoOutro
        run: |
          make

          # Make CIA
          curl -LO https://github.com/ihaveamac/ctr_toolkit/releases/download/make_cia6.4builds/make_cia6.4builds.zip
          unzip -j make_cia6.4builds.zip linux/make_cia
          ./make_cia --srl=NoOutro.dsi

      - name: Upload NoOutro.dsi
        uses: actions/upload-artifact@v2
        with:
          name: NoOutro.dsi
          path: NoOutro.dsi

      - name: Upload NoOutro.cia
        uses: actions/upload-artifact@v2
        with:
          name: NoOutro.cia
          path: NoOutro.cia
