name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - name: Install Python
        run: sudo apt-get -y install python

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build NoOutro
        run: |
          make

          # Make CIA
          curl -LO https://github.com/ihaveamac/ctr_toolkit/releases/download/make_cia6.4builds/make_cia6.4builds.zip
          unzip -j make_cia6.4builds.zip linux/make_cia
          ./make_cia --srl=NoOutro.dsi

      - name: Upload NoOutro.dsi
        uses: AButler/upload-release-assets@v2.0
        with:
          files: NoOutro.dsi
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NoOutro.cia
        uses: AButler/upload-release-assets@v2.0
        with:
          files: NoOutro.cia
          repo-token: ${{ secrets.GITHUB_TOKEN }}
